import { useCallback, useEffect, useMemo, useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { Button, Card, Header, Notice, Screen, ui } from "@/components/ui";
import { colors } from "@/lib/theme";
import { supabase } from "@/lib/supabase";
import { fullName, type AttendanceStatus, type Course, type Registration, type Student } from "@/lib/types";
import { useAuth } from "@/providers/auth";
const statuses: { value: AttendanceStatus; label: string }[] = [{ value: "present", label: "Present" }, { value: "late", label: "Late" }, { value: "excused", label: "Excused" }, { value: "absent", label: "Absent" }];
const iso = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
const latestSunday = () => { const date = new Date(); date.setDate(date.getDate() - date.getDay()); return iso(date); };
const shiftSunday = (value: string, days: number) => { const [y, m, d] = value.split("-").map(Number); const date = new Date(y, m - 1, d); date.setDate(date.getDate() + days); return iso(date); };
export default function Attendance() {
  const { session, teacherId } = useAuth(); const [classes, setClasses] = useState<Course[]>([]); const [classId, setClassId] = useState<number | null>(null); const [students, setStudents] = useState<Student[]>([]); const [registrations, setRegistrations] = useState<Registration[]>([]); const [date, setDate] = useState(latestSunday); const [records, setRecords] = useState<Record<number, AttendanceStatus>>({}); const [busy, setBusy] = useState(true); const [status, setStatus] = useState<{ message?: string; error?: string }>({});
  const loadBase = useCallback(async () => { if (!teacherId) return; const assignmentResult = await supabase.from("teacher_classes").select("class_id").eq("teacher_id", teacherId); const ids = (assignmentResult.data || []).map((row) => row.class_id); if (!ids.length) { setClasses([]); setBusy(false); return; } const [classResult, registrationResult] = await Promise.all([supabase.from("classes").select("*,class_times(display_time)").in("id", ids).eq("is_open", true).order("name"), supabase.from("class_registrations").select("*")]); const registrationsData = registrationResult.data || []; const studentIds = [...new Set(registrationsData.map((row) => row.student_id))]; const studentResult = studentIds.length ? await supabase.from("students").select("*").in("id", studentIds) : { data: [], error: null }; setClasses(classResult.data || []); setClassId((current) => current || classResult.data?.[0]?.id || null); setRegistrations(registrationsData); setStudents(studentResult.data || []); if (assignmentResult.error || classResult.error || registrationResult.error || studentResult.error) setStatus({ error: assignmentResult.error?.message || classResult.error?.message || registrationResult.error?.message || studentResult.error?.message }); setBusy(false); }, [teacherId]);
  useEffect(() => { void Promise.resolve().then(loadBase); }, [loadBase]);
  const roster = useMemo(() => students.filter((student) => registrations.some((row) => row.student_id === student.id && [row.session_1, row.session_2, row.session_3].includes(classId))), [students, registrations, classId]);
  const loadRecords = useCallback(async () => { if (!classId) return; const result = await supabase.from("attendance").select("student_id,status").eq("class_id", classId).eq("class_date", date); setRecords(Object.fromEntries((result.data || []).map((row) => [row.student_id, row.status]))); if (result.error) setStatus({ error: result.error.message }); }, [classId, date]);
  useEffect(() => { void Promise.resolve().then(loadRecords); }, [loadRecords]);
  const save = async (studentId: number, value: AttendanceStatus) => { if (!session || !classId) return; setRecords((current) => ({ ...current, [studentId]: value })); const { error } = await supabase.from("attendance").upsert({ class_id: classId, student_id: studentId, class_date: date, status: value, recorded_by: session.user.id }, { onConflict: "class_id,student_id,class_date" }); if (error) { setStatus({ error: error.message }); await loadRecords(); } };
  const markAll = async () => { if (!session || !classId || !roster.length) return; const payload = roster.map((student) => ({ class_id: classId, student_id: student.id, class_date: date, status: "present", recorded_by: session.user.id })); const { error } = await supabase.from("attendance").upsert(payload, { onConflict: "class_id,student_id,class_date" }); if (error) setStatus({ error: error.message }); else { setRecords(Object.fromEntries(roster.map((student) => [student.id, "present"]))); setStatus({ message: `${roster.length} students marked Present.` }); } };
  return <Screen refreshing={busy}><Header eyebrow="Teacher Portal" title="Attendance" /><Notice {...status} />{!classes.length ? <Card><Text style={ui.body}>No active classes are assigned to this teacher account.</Text></Card> : <><Card><Text style={ui.subheading}>Class</Text><View style={ui.row}>{classes.map((course) => <Pressable key={course.id} onPress={() => setClassId(course.id)} style={[styles.pill, classId === course.id && styles.activePill]}><Text style={[styles.pillText, classId === course.id && styles.activeText]}>{course.name || course.short_name}</Text></Pressable>)}</View><Text style={ui.subheading}>Attendance date</Text><View style={ui.between}><Button title="‹ Previous" kind="secondary" onPress={() => setDate(shiftSunday(date, -7))} /><Text style={ui.subheading}>{date}</Text><Button title="Next ›" kind="secondary" onPress={() => setDate(shiftSunday(date, 7))} /></View><Text style={ui.muted}>Attendance dates are restricted to Sundays.</Text><Button title="Mark All Present" onPress={markAll} disabled={!roster.length} /></Card>{roster.map((student) => <Card key={student.id}><Text style={ui.subheading}>{fullName(student)} {student.chinese_name ? `· ${student.chinese_name}` : ""}</Text><View style={ui.row}>{statuses.map((item) => <Pressable key={item.value} onPress={() => save(student.id, item.value)} style={[styles.status, records[student.id] === item.value && styles[`status_${item.value}`]]}><Text style={[styles.statusText, records[student.id] === item.value && styles.activeText]}>{item.label}</Text></Pressable>)}</View></Card>)}</>}</Screen>;
}
const styles = StyleSheet.create({ pill: { borderWidth: 1, borderColor: colors.border, borderRadius: 20, paddingHorizontal: 12, paddingVertical: 9 }, activePill: { backgroundColor: colors.blue, borderColor: colors.blue }, pillText: { color: colors.navy, fontWeight: "700" }, activeText: { color: colors.white }, status: { borderWidth: 1, borderColor: colors.border, borderRadius: 9, paddingHorizontal: 10, paddingVertical: 9 }, statusText: { color: colors.ink, fontWeight: "700" }, status_present: { backgroundColor: colors.green }, status_late: { backgroundColor: "#b77700" }, status_excused: { backgroundColor: colors.blue }, status_absent: { backgroundColor: colors.red } });
