import { useCallback, useEffect, useMemo, useState } from "react";
import { Text, View } from "react-native";
import * as WebBrowser from "expo-web-browser";
import { BilingualText, Button, Card, Header, Notice, Screen, ui } from "@/components/ui";
import { siteUrl, supabase } from "@/lib/supabase";
import { money, tuitionTotal } from "@/lib/tuition";
import type { Course, Family, Registration, Seat } from "@/lib/types";
import { useAuth } from "@/providers/auth";
import { useLanguage } from "@/providers/language";

type BillingSnapshot = { registrations: Registration[]; classes: Course[]; seats: Seat[]; deposits: { family_id: number; amount: number }[]; usage: { used: number; waiting: number } };
type Payment = { id: number; amount_cents: number; status: string; paid_at?: string; payment_method?: string };
const paymentStatuses: Record<string, { en: string; zh: string }> = { paid: { en: "Paid", zh: "已付款" }, refunded: { en: "Refunded", zh: "已退款" }, pending: { en: "Pending", zh: "待处理" } };
export default function Billing() {
  const { session } = useAuth(); const [family, setFamily] = useState<Family | null>(null); const [billing, setBilling] = useState<BillingSnapshot | null>(null); const [payments, setPayments] = useState<Payment[]>([]); const [busy, setBusy] = useState(true); const [paying, setPaying] = useState(false); const [status, setStatus] = useState<{ message?: string; error?: string }>({});
  const { t } = useLanguage();
  const load = useCallback(async () => { if (!session) return; const familyResult = await supabase.from("families").select("*").eq("user_id", session.user.id).maybeSingle(); setFamily(familyResult.data); if (familyResult.data) { const [snapshot, paymentResult] = await Promise.all([supabase.rpc("waterford_billing_snapshot", { target_family_id: familyResult.data.id }), supabase.from("payments").select("*").eq("family_id", familyResult.data.id).order("paid_at", { ascending: false })]); setBilling(snapshot.data as BillingSnapshot); setPayments(paymentResult.data || []); if (snapshot.error || paymentResult.error) setStatus({ error: snapshot.error?.message || paymentResult.error?.message }); } setBusy(false); }, [session]);
  useEffect(() => { void Promise.resolve().then(load); }, [load]);
  const subtotal = useMemo(() => !billing ? 0 : billing.registrations.reduce((sum, row) => sum + [...new Set([row.session_1, row.session_2, row.session_3].filter((id): id is number => typeof id === "number"))].reduce((courseSum, id) => courseSum + Number(billing.classes.find((course) => course.id === id)?.donation || 0), 0), 0), [billing]);
  const tuition = billing ? tuitionTotal(billing.registrations, billing.classes, billing.seats) : 0; const deposit = billing?.deposits?.find((row) => row.family_id === family?.id)?.amount ?? 0; const due = tuition + deposit; const paid = payments.filter((row) => row.status === "paid").reduce((sum, row) => sum + Number(row.amount_cents || 0) / 100, 0) - payments.filter((row) => row.status === "refunded").reduce((sum, row) => sum + Number(row.amount_cents || 0) / 100, 0);
  const pay = async () => { if (!session) return; setPaying(true); setStatus({}); try { const response = await fetch(`${siteUrl}/api/create-checkout-session`, { method: "POST", headers: { Authorization: `Bearer ${session.access_token}`, "Content-Type": "application/json" } }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Could not start payment. / 无法开始付款。"); await WebBrowser.openBrowserAsync(body.url); await load(); } catch (error) { setStatus({ error: error instanceof Error ? error.message : "Could not start payment. / 无法开始付款。" }); } finally { setPaying(false); } };
  return <Screen refreshing={busy}><Header eyebrow="Family account" eyebrowZh="家庭账户" title="Tuition & Payment" titleZh="学费与付款" /><Notice {...status} />{!family ? <Card><BilingualText en="Complete the family profile first." zh="请先完善家庭资料。" style={ui.body} /></Card> : <><Card><View style={ui.between}><BilingualText en="Tuition subtotal" zh="学费小计" style={ui.body} /><Text style={ui.subheading}>{money(subtotal)}</Text></View><View style={ui.between}><BilingualText en="Waterford discount" zh="Waterford 学费减免" style={ui.body} /><Text style={ui.subheading}>-{money(subtotal - tuition)}</Text></View><View style={ui.between}><BilingualText en="Safety Patrol Deposit" zh="安全巡逻押金" style={ui.body} /><Text style={ui.subheading}>{money(deposit)}</Text></View><View style={ui.divider} /><View style={ui.between}><BilingualText en="Total due" zh="应付总额" style={ui.heading} size={19} /><Text style={ui.amount}>{money(due)}</Text></View><View style={ui.between}><BilingualText en="Payments received" zh="已收款" style={ui.body} /><Text style={ui.subheading}>{money(paid)}</Text></View><Button title={paying ? "Opening secure checkout…" : due <= paid ? "Paid" : "Pay online"} titleZh={paying ? "正在打开安全付款页面…" : due <= paid ? "已付款" : "在线付款"} onPress={pay} disabled={paying || due <= paid || due <= 0} /></Card>{billing && <Card><BilingualText en="Waterford seats" zh="Waterford 免费席位" style={ui.heading} size={19} /><BilingualText en={`${billing.usage.used}/20 free Chinese-course seats used school-wide.`} zh={`全校已使用 ${billing.usage.used}/20 个免费中文课席位。`} style={ui.body} /><BilingualText en="Maliping courses retain the $80 book fee when a free seat is awarded." zh="Maliping 课程获得免费席位后仍需支付 80 美元书本费。" style={ui.muted} size={13} /></Card>}<Card><BilingualText en="Payment history" zh="付款记录" style={ui.heading} size={19} />{payments.length ? payments.map((row) => { const label = paymentStatuses[row.status]; return <View key={row.id} style={ui.between}><Text style={ui.body}>{label ? t(label.en, label.zh) : row.status} · {row.paid_at ? new Date(row.paid_at).toLocaleDateString() : ""}</Text><Text style={ui.subheading}>{money(row.amount_cents / 100)}</Text></View>; }) : <BilingualText en="No online payments recorded." zh="暂无在线付款记录。" style={ui.muted} size={13} />}</Card></>}</Screen>;
}
