import { useCallback, useEffect, useMemo, useState } from "react";
import { Text, View } from "react-native";
import * as WebBrowser from "expo-web-browser";
import { Button, Card, Header, Notice, Screen, ui } from "@/components/ui";
import { siteUrl, supabase } from "@/lib/supabase";
import { money, tuitionTotal } from "@/lib/tuition";
import type { Course, Family, Registration, Seat } from "@/lib/types";
import { useAuth } from "@/providers/auth";

type BillingSnapshot = { registrations: Registration[]; classes: Course[]; seats: Seat[]; deposits: { family_id: number; amount: number }[]; usage: { used: number; waiting: number } };
type Payment = { id: number; amount_cents: number; status: string; paid_at?: string; payment_method?: string };
export default function Billing() {
  const { session } = useAuth(); const [family, setFamily] = useState<Family | null>(null); const [billing, setBilling] = useState<BillingSnapshot | null>(null); const [payments, setPayments] = useState<Payment[]>([]); const [busy, setBusy] = useState(true); const [paying, setPaying] = useState(false); const [status, setStatus] = useState<{ message?: string; error?: string }>({});
  const load = useCallback(async () => { if (!session) return; const familyResult = await supabase.from("families").select("*").eq("user_id", session.user.id).maybeSingle(); setFamily(familyResult.data); if (familyResult.data) { const [snapshot, paymentResult] = await Promise.all([supabase.rpc("waterford_billing_snapshot", { target_family_id: familyResult.data.id }), supabase.from("payments").select("*").eq("family_id", familyResult.data.id).order("paid_at", { ascending: false })]); setBilling(snapshot.data as BillingSnapshot); setPayments(paymentResult.data || []); if (snapshot.error || paymentResult.error) setStatus({ error: snapshot.error?.message || paymentResult.error?.message }); } setBusy(false); }, [session]);
  useEffect(() => { void Promise.resolve().then(load); }, [load]);
  const subtotal = useMemo(() => !billing ? 0 : billing.registrations.reduce((sum, row) => sum + [...new Set([row.session_1, row.session_2, row.session_3].filter((id): id is number => typeof id === "number"))].reduce((courseSum, id) => courseSum + Number(billing.classes.find((course) => course.id === id)?.donation || 0), 0), 0), [billing]);
  const tuition = billing ? tuitionTotal(billing.registrations, billing.classes, billing.seats) : 0; const deposit = billing?.deposits?.find((row) => row.family_id === family?.id)?.amount ?? 0; const due = tuition + deposit; const paid = payments.filter((row) => row.status === "paid").reduce((sum, row) => sum + Number(row.amount_cents || 0) / 100, 0) - payments.filter((row) => row.status === "refunded").reduce((sum, row) => sum + Number(row.amount_cents || 0) / 100, 0);
  const pay = async () => { if (!session) return; setPaying(true); setStatus({}); try { const response = await fetch(`${siteUrl}/api/create-checkout-session`, { method: "POST", headers: { Authorization: `Bearer ${session.access_token}`, "Content-Type": "application/json" } }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Could not start payment."); await WebBrowser.openBrowserAsync(body.url); await load(); } catch (error) { setStatus({ error: error instanceof Error ? error.message : "Could not start payment." }); } finally { setPaying(false); } };
  return <Screen refreshing={busy}><Header eyebrow="Family account" title="Tuition & Payment" /><Notice {...status} />{!family ? <Card><Text style={ui.body}>Complete the family profile first.</Text></Card> : <><Card><View style={ui.between}><Text style={ui.body}>Tuition subtotal</Text><Text style={ui.subheading}>{money(subtotal)}</Text></View><View style={ui.between}><Text style={ui.body}>Waterford discount</Text><Text style={ui.subheading}>-{money(subtotal - tuition)}</Text></View><View style={ui.between}><Text style={ui.body}>Safety Patrol Deposit</Text><Text style={ui.subheading}>{money(deposit)}</Text></View><View style={ui.divider} /><View style={ui.between}><Text style={ui.heading}>Total due</Text><Text style={ui.amount}>{money(due)}</Text></View><View style={ui.between}><Text style={ui.body}>Payments received</Text><Text style={ui.subheading}>{money(paid)}</Text></View><Button title={paying ? "Opening secure checkout…" : due <= paid ? "Paid" : "Pay online"} onPress={pay} disabled={paying || due <= paid || due <= 0} /></Card>{billing && <Card><Text style={ui.heading}>Waterford seats</Text><Text style={ui.body}>{billing.usage.used}/20 free Chinese-course seats used school-wide.</Text><Text style={ui.muted}>Maliping courses retain the $80 book fee when a free seat is awarded.</Text></Card>}<Card><Text style={ui.heading}>Payment history</Text>{payments.length ? payments.map((row) => <View key={row.id} style={ui.between}><Text style={ui.body}>{row.status} · {row.paid_at ? new Date(row.paid_at).toLocaleDateString() : ""}</Text><Text style={ui.subheading}>{money(row.amount_cents / 100)}</Text></View>) : <Text style={ui.muted}>No online payments recorded.</Text>}</Card></>}</Screen>;
}
