import { useCallback, useEffect, useState } from "react";
import { Alert, Text, View } from "react-native";
import { Button, Card, Field, Header, Notice, Screen, ui } from "@/components/ui";
import { supabase } from "@/lib/supabase";
import { fullName, type Family, type Student } from "@/lib/types";
import { useAuth } from "@/providers/auth";

const emptyFamily = { parent_first_name: "", parent_last_name: "", parent_chinese_name: "", phone: "", address: "", city: "", state: "CT", zip: "" };
const emptyStudent = { first_name: "", last_name: "", chinese_name: "", gender: "", birth_year: "" };
export default function Students() {
  const { session } = useAuth(); const [family, setFamily] = useState<Partial<Family>>(emptyFamily); const [students, setStudents] = useState<Student[]>([]); const [student, setStudent] = useState(emptyStudent); const [editing, setEditing] = useState<number | null>(null); const [busy, setBusy] = useState(true); const [status, setStatus] = useState<{ message?: string; error?: string }>({});
  const load = useCallback(async () => { if (!session) return; const familyResult = await supabase.from("families").select("*").eq("user_id", session.user.id).maybeSingle(); if (familyResult.error) setStatus({ error: familyResult.error.message }); else { setFamily({ ...emptyFamily, ...(familyResult.data || {}) }); if (familyResult.data) { const result = await supabase.from("students").select("*").eq("family_id", familyResult.data.id).order("created_at"); setStudents(result.data || []); if (result.error) setStatus({ error: result.error.message }); } } setBusy(false); }, [session]);
  useEffect(() => { void Promise.resolve().then(load); }, [load]);
  const saveFamily = async () => { if (!session) return; const payload = { parent_first_name: family.parent_first_name || null, parent_last_name: family.parent_last_name || null, parent_chinese_name: family.parent_chinese_name || null, phone: family.phone || null, address: family.address || null, city: family.city || null, state: family.state || null, zip: family.zip || null, email: session.user.email, user_id: session.user.id, waterford_resident: String(family.city || "").trim().toLowerCase() === "waterford" }; const result = await supabase.from("families").upsert(payload, { onConflict: "user_id" }).select().single(); if (result.error) setStatus({ error: result.error.message }); else { setFamily(result.data); setStatus({ message: "Family profile saved." }); } };
  const saveStudent = async () => { if (!family.id) return setStatus({ error: "Save the family profile first." }); const payload = { ...student, family_id: family.id, birth_year: student.birth_year || null }; const result = editing ? await supabase.from("students").update(payload).eq("id", editing) : await supabase.from("students").insert(payload); if (result.error) setStatus({ error: result.error.message }); else { setStudent(emptyStudent); setEditing(null); setStatus({ message: editing ? "Student updated." : "Student added." }); await load(); } };
  const remove = (row: Student) => Alert.alert("Delete student", `Delete ${fullName(row)} and this student's registration?`, [{ text: "Cancel", style: "cancel" }, { text: "Delete", style: "destructive", onPress: async () => { const { error } = await supabase.from("students").delete().eq("id", row.id); if (error) setStatus({ error: error.message }); else await load(); } }]);
  const familyField = (key: keyof typeof emptyFamily, value: string) => setFamily((current) => ({ ...current, [key]: value }));
  const studentField = (key: keyof typeof emptyStudent, value: string) => setStudent((current) => ({ ...current, [key]: value }));
  return <Screen refreshing={busy}><Header eyebrow="Family account" title="Family & Students" /><Notice {...status} /><Card><Text style={ui.heading}>Parent profile</Text><Field label="Parent first name" value={family.parent_first_name || ""} onChangeText={(v) => familyField("parent_first_name", v)} /><Field label="Parent last name" value={family.parent_last_name || ""} onChangeText={(v) => familyField("parent_last_name", v)} /><Field label="中文姓名 Chinese name" value={family.parent_chinese_name || ""} onChangeText={(v) => familyField("parent_chinese_name", v)} /><Field label="Phone" value={family.phone || ""} onChangeText={(v) => familyField("phone", v)} keyboardType="phone-pad" /><Field label="Address" value={family.address || ""} onChangeText={(v) => familyField("address", v)} /><Field label="City" value={family.city || ""} onChangeText={(v) => familyField("city", v)} /><View style={ui.row}><View style={{ flex: 1 }}><Field label="State" value={family.state || ""} onChangeText={(v) => familyField("state", v)} /></View><View style={{ flex: 1 }}><Field label="ZIP" value={family.zip || ""} onChangeText={(v) => familyField("zip", v)} keyboardType="number-pad" /></View></View><Button title="Save family profile" onPress={saveFamily} /></Card>
    {students.map((row) => <Card key={row.id}><View style={ui.between}><View><Text style={ui.subheading}>{fullName(row) || `Student ${row.id}`}</Text><Text style={ui.muted}>{[row.chinese_name, row.birth_year].filter(Boolean).join(" · ")}</Text></View><View style={ui.row}><Button title="Edit" kind="secondary" onPress={() => { setEditing(row.id); setStudent({ ...emptyStudent, first_name: row.first_name || "", last_name: row.last_name || "", chinese_name: row.chinese_name || "", gender: row.gender || "", birth_year: row.birth_year || "" }); }} /><Button title="Delete" kind="danger" onPress={() => remove(row)} /></View></View></Card>)}
    <Card><Text style={ui.heading}>{editing ? "Edit student" : "Add student"}</Text><Field label="First name" value={student.first_name} onChangeText={(v) => studentField("first_name", v)} /><Field label="Last name" value={student.last_name} onChangeText={(v) => studentField("last_name", v)} /><Field label="中文姓名 Chinese name" value={student.chinese_name} onChangeText={(v) => studentField("chinese_name", v)} /><Field label="Gender" value={student.gender} onChangeText={(v) => studentField("gender", v)} /><Field label="Birth year" value={student.birth_year} onChangeText={(v) => studentField("birth_year", v)} keyboardType="number-pad" /><Button title={editing ? "Update student" : "Add student"} onPress={saveStudent} disabled={!student.first_name && !student.last_name} />{editing && <Button title="Cancel edit" kind="secondary" onPress={() => { setEditing(null); setStudent(emptyStudent); }} />}</Card></Screen>;
}
