create table if not exists sccs.payments (
  id bigint generated by default as identity primary key,
  family_id bigint not null references sccs.families(id) on delete cascade,
  method text not null check (method in ('cash', 'check', 'online')),
  amount_cents integer not null check (amount_cents >= 0),
  currency text not null default 'usd',
  paid_at timestamptz not null default now(),
  status text not null default 'paid' check (status in ('pending', 'paid', 'failed', 'refunded', 'cancelled')),
  check_number text,
  stripe_checkout_session_id text unique,
  stripe_payment_intent_id text,
  stripe_charge_id text,
  card_brand text,
  card_last4 text,
  card_exp_month integer,
  card_exp_year integer,
  notes text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists payments_family_id_idx on sccs.payments(family_id);
create index if not exists payments_paid_at_idx on sccs.payments(paid_at desc);
create index if not exists payments_method_idx on sccs.payments(method);

alter table sccs.payments enable row level security;

grant usage on schema sccs to authenticated, service_role;
grant select, insert, update, delete on sccs.payments to authenticated, service_role;
grant usage, select on sequence sccs.payments_id_seq to authenticated, service_role;

drop policy if exists "Families view own payments" on sccs.payments;
create policy "Families view own payments" on sccs.payments
for select to authenticated
using (
  exists (
    select 1
    from sccs.families family
    where family.id = payments.family_id
      and family.user_id = (select auth.uid())
  )
);

drop policy if exists "Admins manage payments" on sccs.payments;
create policy "Admins manage payments" on sccs.payments
for all to authenticated
using (
  (select private.current_user_has_role(array[
    'sccs_admin_team_role',
    'sccs_superadmin_role'
  ]::sccs.app_role[]))
)
with check (
  (select private.current_user_has_role(array[
    'sccs_admin_team_role',
    'sccs_superadmin_role'
  ]::sccs.app_role[]))
);
