-- SCCS SQL Server to Supabase/PostgreSQL migration.
-- Run in the Supabase SQL editor before enabling family accounts.

create schema if not exists sccs;

create table if not exists sccs.class_times (
  id integer generated by default as identity primary key,
  legacy_class_time_id integer unique,
  display_time varchar(50),
  notes varchar(50)
);

create table if not exists sccs.teachers (
  id bigint generated by default as identity primary key,
  legacy_teacher_id integer unique,
  short_name varchar(50),
  first_name varchar(50),
  last_name varchar(50),
  email_1 varchar(254),
  phone_1 varchar(50),
  email_2 varchar(254),
  phone_2 varchar(50)
);

create table if not exists sccs.classes (
  id bigint generated by default as identity primary key,
  legacy_class_id integer unique,
  short_name varchar(50),
  name varchar(100),
  maximum integer check (maximum is null or maximum >= 0),
  class_time_id integer references sccs.class_times(id) on delete set null,
  type varchar(50),
  donation integer check (donation is null or donation >= 0),
  classroom varchar(50),
  teacher_short_name varchar(50),
  is_open boolean not null default true,
  equivalent varchar(50),
  textbook varchar(100)
);

create table if not exists sccs.families (
  id bigint generated by default as identity primary key,
  user_id uuid unique references auth.users(id) on delete cascade,
  legacy_family_id integer unique,
  email varchar(254),
  family_name varchar(50),
  parent_first_name varchar(50),
  parent_last_name varchar(50),
  address varchar(100),
  city varchar(50),
  state varchar(50),
  zip varchar(20),
  phone varchar(50),
  parent_chinese_name varchar(50),
  wechat varchar(50),
  legacy_create_ip text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists sccs.students (
  id bigint generated by default as identity primary key,
  family_id bigint references sccs.families(id) on delete cascade,
  legacy_student_id integer unique,
  legacy_family_id integer,
  first_name varchar(50),
  last_name varchar(50),
  gender varchar(50),
  birth_year varchar(50),
  chinese_name varchar(50),
  legacy_create_ip text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists sccs.class_registrations (
  id bigint generated by default as identity primary key,
  legacy_class_registration_id integer unique,
  student_id bigint unique references sccs.students(id) on delete cascade,
  legacy_student_id integer,
  session_1 bigint references sccs.classes(id) on delete set null,
  session_2 bigint references sccs.classes(id) on delete set null,
  session_3 bigint references sccs.classes(id) on delete set null,
  legacy_session_1 integer,
  legacy_session_2 integer,
  legacy_session_3 integer,
  registered_at timestamptz not null default now(),
  registration_ip text
);

create table if not exists sccs.family_registrations (
  id bigint generated by default as identity primary key,
  legacy_family_registration_id integer unique,
  family_id bigint references sccs.families(id) on delete cascade,
  legacy_family_id integer,
  handbook_agreement boolean not null default false,
  medical_release boolean not null default false,
  photo_agreement boolean not null default false,
  pfizer_match boolean not null default false,
  late_fee integer,
  registration_fee integer,
  created_at timestamptz not null default now(),
  create_ip text,
  pay_1_cash integer,
  pay_1_check integer,
  pay_1_check_number varchar(50),
  pay_1_check_name varchar(50),
  pay_2_cash integer,
  pay_2_check integer,
  pay_2_check_number varchar(50),
  pay_2_check_name varchar(50),
  form_status varchar(50),
  pay_3_cash integer,
  pay_3_check integer,
  pay_3_refund integer,
  pay_3_check_number varchar(50),
  pay_3_check_name varchar(50),
  day_3_refund integer,
  day_2_refund integer,
  pay_4_refund integer,
  pay_4_refund_note varchar(50),
  pay_4_cash integer,
  pay_4_check_number varchar(50),
  pay_4_check_name varchar(50),
  pay_4_check integer,
  pay_5_cash integer,
  pay_5_check integer,
  pay_5_check_number varchar(50),
  pay_5_check_name varchar(50),
  pay_5_refund varchar(50),
  pfizer_employee_name varchar(50),
  pfizer_email varchar(254),
  patrol_deposit integer,
  volunteer_name varchar(50)
);

create table if not exists public.feedback (
  id bigint generated always as identity primary key,
  name varchar(100) not null,
  email varchar(254) not null,
  phone varchar(50),
  message text not null check (char_length(message) <= 5000),
  created_at timestamptz not null default now()
);

create index if not exists students_family_id_idx on sccs.students(family_id);
create index if not exists class_registrations_student_id_idx on sccs.class_registrations(student_id);
create index if not exists family_registrations_family_id_idx on sccs.family_registrations(family_id);

create or replace function sccs.set_updated_at()
returns trigger language plpgsql set search_path = '' as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists families_set_updated_at on sccs.families;
create trigger families_set_updated_at before update on sccs.families
for each row execute function sccs.set_updated_at();
drop trigger if exists students_set_updated_at on sccs.students;
create trigger students_set_updated_at before update on sccs.students
for each row execute function sccs.set_updated_at();

alter table sccs.class_times enable row level security;
alter table sccs.teachers enable row level security;
alter table sccs.classes enable row level security;
alter table sccs.families enable row level security;
alter table sccs.students enable row level security;
alter table sccs.class_registrations enable row level security;
alter table sccs.family_registrations enable row level security;
alter table public.feedback enable row level security;

grant usage on schema sccs to anon, authenticated;
grant select on sccs.class_times, sccs.teachers, sccs.classes to anon, authenticated;
grant select, insert, update, delete on sccs.families, sccs.students,
  sccs.class_registrations, sccs.family_registrations to authenticated;
grant insert on public.feedback to anon, authenticated;
grant usage, select on all sequences in schema sccs to authenticated;
grant usage, select on sequence public.feedback_id_seq to anon, authenticated;

drop policy if exists "Public class times" on sccs.class_times;
create policy "Public class times" on sccs.class_times for select using (true);
drop policy if exists "Public teachers" on sccs.teachers;
create policy "Public teachers" on sccs.teachers for select using (true);
drop policy if exists "Public classes" on sccs.classes;
create policy "Public classes" on sccs.classes for select using (true);

drop policy if exists "Users manage their family" on sccs.families;
create policy "Users manage their family" on sccs.families
for all to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users manage their students" on sccs.students;
create policy "Users manage their students" on sccs.students
for all to authenticated
using (exists (
  select 1 from sccs.families f
  where f.id = family_id and f.user_id = (select auth.uid())
))
with check (exists (
  select 1 from sccs.families f
  where f.id = family_id and f.user_id = (select auth.uid())
));

drop policy if exists "Users manage class registrations" on sccs.class_registrations;
create policy "Users manage class registrations" on sccs.class_registrations
for all to authenticated
using (exists (
  select 1 from sccs.students s join sccs.families f on f.id = s.family_id
  where s.id = student_id and f.user_id = (select auth.uid())
))
with check (exists (
  select 1 from sccs.students s join sccs.families f on f.id = s.family_id
  where s.id = student_id and f.user_id = (select auth.uid())
));

drop policy if exists "Users manage family registrations" on sccs.family_registrations;
create policy "Users manage family registrations" on sccs.family_registrations
for all to authenticated
using (exists (
  select 1 from sccs.families f
  where f.id = family_id and f.user_id = (select auth.uid())
))
with check (exists (
  select 1 from sccs.families f
  where f.id = family_id and f.user_id = (select auth.uid())
));

drop policy if exists "Anyone submits feedback" on public.feedback;
create policy "Anyone submits feedback" on public.feedback
for insert to anon, authenticated
with check (
  char_length(name) between 1 and 100
  and char_length(email) between 3 and 254
  and char_length(message) between 1 and 5000
);

-- FAMILY.Mima is deliberately excluded. Passwords belong in Supabase Auth.
-- Preserve old numeric IDs in legacy_* fields while importing old rows.
